### ISSUE TITLE
Multiple Google Account

### ISSUE THREAD

**Issue by johnss** [cobalt232/blackberrymanager#28]
i have 2 google account set, example i want to use exampleA@gmail.com but it only show exampleB@gmail.com as an option, how to use exampleA as login account?

**Comment by cobalt232** [comment]
Please be more specific with your request. Are we talking about the BlackBerry Manager itself or about an BlackBerry app that is downloaded with the manager?

**Comment by cobalt232** [comment]
Closed, as no futher information is provided.

**Comment by johnss** [comment]
please reopen issue as im busy few nonths ago

in blackberry manager there is no way to select google account

when i login im only using account B when account A are exist, i want to use account A 

if there are multiple google account set it just conect to one of them randomly there is no way to choose, if i want to connect using account A i need to logout/unset the account B in android settings

**Comment by cobalt232** [comment]
Currently, BlackBerry Manager uses Account[0], which is the first Account that was created on the device. In most cases this is suitable. The problem with multiple account is, that you need to accept the Play Store TOS (Terms of Service) for each account in order to download apps via the API. With your primary account, you don't need to bother about that, because if a new TOS is published by Google, it is automatically accepted by Play Store for that account. I might add this feature sometime in the future, but not right now.
